#! /bin/sh
### BEGIN INIT INFO
# Provides:          piphoned
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Piphoned SIP daemon
# Description:       Daemon managing all the actual telephone stuff by
#                    building up a SIP client connection.
### END INIT INFO

# Author: Marvin Gülker <m-guelker@quintilianus.eu>

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
export PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
DESC="Piphoned SIP daemon"
NAME=piphoned
DAEMON=/usr/sbin/$NAME
DAEMON_ARGS="-l 7"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

case "$1" in
  start)
      log_daemon_msg "Starting $DESC" "$NAME"
      $DAEMON $DAEMON_ARGS start
      log_end_msg $?
      ;;
  stop)
      log_daemon_msg "Stopping $DESC" "$NAME"
      $DAEMON $DAEMON_ARGS stop
      log_end_msg $?
      ;;
  status)
      status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
      ;;
  restart|force-reload)
      log_daemon_msg "Restarting $DESC" "$NAME"
      $DAEMON $DAEMON_ARGS restart
      log_end_msg $?
      ;;
  *)
      echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
      exit 3
      ;;
esac

:
